- name: Create user and group for Elasticsearch and Kibana
  user:
    name: "{{ item }}"
    system: true
    shell: /sbin/nologin
    create_home: false
  loop:
    - "{{ elasticsearch_user }}"
    - "{{ kibana_user }}"

- name: Create directories for Elasticsearch
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: '0755'
  loop:
    - "{{ elasticsearch_install_dir }}"
    - "{{ elasticsearch_data_dir }}"
    - "{{ elasticsearch_config_dir }}"

- name: Create directories for Kibana
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: '0755'
  loop:
    - "{{ kibana_install_dir }}"
    - "{{ kibana_config_dir }}"

- name: Download and install Elasticsearch
  unarchive:
    src: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-linux-x86_64.tar.gz"
    dest: "{{ elasticsearch_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"

- name: Download and install Kibana
  unarchive:
    src: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    dest: "{{ kibana_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"

- name: Configure systemd service for Elasticsearch
  template:
    src: "elasticsearch.service.j2"
    dest: "/etc/systemd/system/elasticsearch.service"
    mode: '0644'
  notify: restart elasticsearch

- name: Configure systemd service for Kibana
  template:
    src: "kibana.service.j2"
    dest: "/etc/systemd/system/kibana.service"
    mode: '0644'
  notify: restart kibana

- name: Configure Elasticsearch
  template:
    src: "elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: '0644'
  notify: restart elasticsearch

- name: Configure Kibana
  template:
    src: "kibana.yml.j2"
    dest: "/etc/kibana/kibana.yml"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: '0644'
  notify: restart kibana


- name: Enable and start Elasticsearch service
  systemd_service:
    name: elasticsearch
    enabled: yes
    state: started
    daemon_reload: true

- name: Enable and start Kibana service
  systemd_service:
    name: kibana
    enabled: yes
    state: started
    daemon_reload: true
